# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and lock file if available
COPY package.json package-lock.json* ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the TypeScript code
RUN npm run build

CMD [ "node", "build/spotify-mcp-server.js" ]
